name: CI

on:
  push:
    branches: [ 'main' ]
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'renovate.json'
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  code-style:
    name: Code style
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '8.3' ]
    steps:
      - name: Check out the repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Check PHP Version
        run: php -v

      - name: Update dependencies with composer
        run: composer update --no-interaction --no-ansi --no-progress

      - name: Load ECS Cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: /tmp/ecs
          key: ${{ runner.os }}-ecs-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-ecs-

      - name: Create cache directory
        run: mkdir -p /tmp/ecs

      - name: Run ECS
        run: ./vendor/bin/ecs --config=ecs.php check

  code-quality:
    name: Code quality
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '8.3' ]
    steps:
      - name: Check out the repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Check PHP Version
        run: php -v

      - name: Update dependencies with composer
        run: composer update --no-interaction --no-ansi --no-progress

      - name: Load Rector Cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: /tmp/rector
          key: ${{ runner.os }}-rector-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-rector-

      - name: Create cache directory
        run: mkdir -p /tmp/rector

      - name: Run Rector
        run: ./vendor/bin/rector --config=rector.php process --dry-run

  static-analysis:
    name: Static analysis (PHPStan)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.3' ]
      fail-fast: false
    steps:
      - name: Check out the repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Check PHP Version
        run: php -v

      - name: Update dependencies with composer
        run: composer update --no-interaction --no-ansi --no-progress

      - name: Load PHPStan Cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: /tmp/phpstan
          key: ${{ runner.os }}-phpstan-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-phpstan-

      - name: Create cache directory
        run: mkdir -p /tmp/phpstan

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze --configuration phpstan.neon

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '8.3', '8.4' ]
        symfony-version: [ '6.4.*', '7.1.*' ]
      fail-fast: false
    steps:
      - name: Check out the repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2

      - name: Check PHP Version
        run: php -v

      - name: Specify symfony version
        uses: jacobtomlinson/gha-find-replace@f1069b438f125e5395d84d1c6fd3b559a7880cb5 # 3.0.5
        with:
          include: 'composer.json'
          find: '^6.4|^7.1'
          replace: '${{ matrix.symfony-version }}'
          regex: false

      - name: Update dependencies with composer
        run: composer update --no-interaction --no-ansi --no-progress

      - name: Run PHPUnit
        run: XDEBUG_MODE=coverage ./vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover ./coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
        with:
          files: ./coverage.xml
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}