name: CI

on:
  push:
    branches: [ 'main' ]
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'renovate.json'
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  code-style:
    name: Code style
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '8.3' ]
    steps:
      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PHP
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # 2.32.0
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Check PHP Version
        run: php -v

      - name: Update dependencies with composer
        run: composer update --no-interaction --no-ansi --no-progress

      - name: Load ECS Cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: /tmp/ecs
          key: ${{ runner.os }}-ecs-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-ecs-

      - name: Create cache directory
        run: mkdir -p /tmp/ecs

      - name: Run ECS
        run: ./vendor/bin/ecs --config=ecs.php check

  code-quality:
    name: Code quality
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '8.3' ]
    steps:
      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PHP
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # 2.32.0
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Check PHP Version
        run: php -v

      - name: Update dependencies with composer
        run: composer update --no-interaction --no-ansi --no-progress

      - name: Load Rector Cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: /tmp/rector
          key: ${{ runner.os }}-rector-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-rector-

      - name: Create cache directory
        run: mkdir -p /tmp/rector

      - name: Run Rector
        run: ./vendor/bin/rector --config=rector.php process --dry-run

  static-analysis:
    name: Static analysis (PHPStan)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.3' ]
      fail-fast: false
    steps:
      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PHP
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # 2.32.0
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Check PHP Version
        run: php -v

      - name: Update dependencies with composer
        run: composer update --no-interaction --no-ansi --no-progress

      - name: Load PHPStan Cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: /tmp/phpstan
          key: ${{ runner.os }}-phpstan-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-phpstan-

      - name: Create cache directory
        run: mkdir -p /tmp/phpstan

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze --configuration phpstan.neon

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '8.3', '8.4' ]
        symfony-version: [ '6.4.*', '7.1.*' ]
      fail-fast: false
    steps:
      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PHP
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # 2.32.0
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2

      - name: Check PHP Version
        run: php -v

      - name: Specify symfony version
        uses: jacobtomlinson/gha-find-replace@f1069b438f125e5395d84d1c6fd3b559a7880cb5 # 3.0.5
        with:
          include: 'composer.json'
          find: '^6.4|^7.1'
          replace: '${{ matrix.symfony-version }}'
          regex: false

      - name: Update dependencies with composer
        run: composer update --no-interaction --no-ansi --no-progress

      - name: Run PHPUnit
        run: XDEBUG_MODE=coverage ./vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover ./coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        with:
          files: ./coverage.xml
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}