name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  code-style:
    name: Code style
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-versions: [ '8.1' ]
      fail-fast: false
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      - name: Setup PHP
        uses: shivammathur/setup-php@9f51892bda551c29f469a2b3d8514b6d2ed84dc9
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
      - name: Check PHP Version
        run: php -v
      - name: Update dependencies with composer
        run: composer update --no-interaction --no-ansi --no-progress
      - name: Run ECS
        run: ./vendor/bin/ecs --config=ecs.php check

  code-quality:
    name: Code quality
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-versions: [ '8.1' ]
      fail-fast: false
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      - name: Setup PHP
        uses: shivammathur/setup-php@9f51892bda551c29f469a2b3d8514b6d2ed84dc9
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
      - name: Check PHP Version
        run: php -v
      - name: Update dependencies with composer
        run: composer update --no-interaction --no-ansi --no-progress
      - name: Run Rector
        run: ./vendor/bin/rector --config=rector.php process --dry-run

  static-analysis:
    name: Static analysis (PHPStan)
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-versions: [ '8.1' ]
      fail-fast: false
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      - name: Setup PHP
        uses: shivammathur/setup-php@9f51892bda551c29f469a2b3d8514b6d2ed84dc9
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
      - name: Check PHP Version
        run: php -v
      - name: Update dependencies with composer
        run: composer update --no-interaction --no-ansi --no-progress
      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze --configuration phpstan.neon

  unit-tests:
    name: Unit tests
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-versions: [ '8.1', '8.2', '8.3' ]
      fail-fast: false
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      - name: Setup PHP
        uses: shivammathur/setup-php@9f51892bda551c29f469a2b3d8514b6d2ed84dc9
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
      - name: Check PHP Version
        run: php -v
      - name: Update dependencies with composer
        run: composer update --no-interaction --no-ansi --no-progress
      - name: Run PHPUnit
        run: XDEBUG_MODE=coverage ./vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover ./coverage.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@1f30f8b7576840249fdd6164afd42b97cb1af0ab
        with:
          files: ./coverage.xml
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}